# *****Components*****
components:
    # Request examples
    requestBodies:
        AddProduct:
            type: Object
            properties:
                title:
                    type: String
                originalTitle:
                    type: String
                originalTitleRomanised:
                    type: String
                image:
                    type: String
                description:
                    type: String
                director:
                    type: String
                producer:
                    type: String
                releaseYear:
                    type: Number
                minDuration:
                    type: Number
                info:
                    type: String
                price:
                    type: Number
            example:
                title: Castle in the Sky
                originalTitle: 天空の城ラピュタ
                originalTitleRomanised: Tenkū no shiro Rapyuta
                image: https://image.tmdb.org/t/p/w600_and_h900_bestv2/npOnzAbLh6VOIu3naU5QaEcTepo.jpg
                description: The orphan Sheeta inherited a mysterious crystal that links her to the mythical sky-kingdom of Laputa. With the help of resourceful Pazu and a rollicking band of sky pirates, she makes her way to the ruins of the once-great civilization. Sheeta and Pazu must outwit the evil Muska, who plans to use Laputa's science to make himself ruler of the world
                director: Hayao Miyazaki
                producer: Isao Takahata
                releaseYear: 1986
                minDuration: 124
                info: https://www.imdb.com/title/tt0092067/?ref_=fn_al_tt_1
                price: 110
        UpdateProduct:
            type: Object
            properties:
                title:
                    type: String
                originalTitle:
                    type: String
                originalTitleRomanised:
                    type: String
                image:
                    type: String
                description:
                    type: String
                director:
                    type: String
                producer:
                    type: String
                releaseYear:
                    type: Number
                minDuration:
                    type: Number
                info:
                    type: String
                price:
                    type: Number
            example:
                title: Changed
                originalTitle: Changed
                originalTitleRomanised: Changed
                image: https://image.tmdb.org/t/p/w600_and_h900_bestv2/npOnzAbLh6VOIu3naU5QaEcTepo.jpg
                description: The orphan Sheeta inherited a mysterious crystal that links her to the mythical sky-kingdom of Laputa. With the help of resourceful Pazu and a rollicking band of sky pirates, she makes her way to the ruins of the once-great civilization. Sheeta and Pazu must outwit the evil Muska, who plans to use Laputa's science to make himself ruler of the world
                director: Changed
                producer: Changed
                releaseYear: 1986
                minDuration: 124
                info: https://www.imdb.com/title/tt0092067/?ref_=fn_al_tt_1
                price: 110
    # OK response
    responseBodies:
        ProductAdded:
            type: Object
            properties:
                results:
                    type: String
            example:
                results: product created
        GetProducts:
            type: Object
            properties:
                results:
                    type: Array
            example:
                results: []
        OneProduct:
            type: Object
            properties:
                results:
                    type: Object
            example:
                results: {}
        ProductUpdated:
            type: Object
            properties:
                results:
                    type: Object
            example:
                results: 'product acepted-updated'
        ProductDeleted:
            type: Object
            properties:
                results:
                    type: Object
            example:
                results: product deleted
    # Error response
    responseErrorBodies:
        WrongFields:
            type: Object
            properties:
                errors:
                    type: Array
            example:
                errors: ['Wrong fields...']
        ProductNotFound:
            type: Object
            properties:
                errors:
                    type: Object
            example:
                errors: product not found
# *****Paths*****
paths:
    /api/products:
        post:
            summary: Add a product to the application
            tags:
                - Products
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/requestBodies/AddProduct'
            responses:
                '201':
                    description: OK (product created)
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/responseBodies/ProductAdded'
                '400':
                    description: Invalid Body Fields - Bad Request
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/responseErrorBodies/WrongFields'
        get:
            summary: Returns all products of the application
            tags:
                - Products
            responses:
                '200':
                    description: OK (products)
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/responseBodies/GetProducts'
    /api/products/{productId}:
        get:
            summary: Return a product according to its id
            tags:
                - Products
            parameters:
                - name: productId
                  in: path
                  required: true
                  description: productId(uuidV4)
                  schema:
                      type: string
            responses:
                '200':
                    description: OK (product)
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/responseBodies/OneProduct'
                '400':
                    description: Invalid Params Field - Bad Request
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/responseErrorBodies/WrongFields'
                '404':
                    description: Invalid productId(uuidv4) - Not Found
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/responseErrorBodies/ProductNotFound'
        put:
            summary: Update product by id
            tags:
                - Products
            parameters:
                - name: productId
                  in: path
                  required: true
                  description: productId(uuidV4)
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/requestBodies/UpdateProduct'
            responses:
                '202':
                    description: OK (product Updated)
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/responseBodies/ProductUpdated'
                '400':
                    description: Invalid Body | Params Fields - Bad Request
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/responseErrorBodies/WrongFields'
                '404':
                    description: Invalid productId(uuidv4) - Not Found
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/responseErrorBodies/ProductNotFound'
        delete:
            summary: Remove a product according to its id
            tags:
                - Products
            parameters:
                - name: productId
                  in: path
                  required: true
                  description: productId(uuidV4)
                  schema:
                      type: string
            responses:
                '200':
                    description: OK (product deleted)
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/responseBodies/ProductDeleted'
                '400':
                    description: Invalid Params Field - Bad Request
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/responseErrorBodies/WrongFields'
                '404':
                    description: Invalid productId(uuidv4) - Not Found
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: '#/components/responseErrorBodies/ProductNotFound'
